# this is for MkDocs, to turn the .md files produced by Documenter into .html files
site_name:        PhyloPlots.jl
repo_url:         https://github.com/cecileane/PhyloPlots.jl
site_description: Display utilities for phylogenetic trees and networks
site_author:      C&eacute;cile An&eacute;

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent:  'teal'
  logo: 'networky_a.png' # 'snaq_small.png'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite

docs_dir: 'build'

nav:
  - home: index.md
  - library:
    - public: lib/public.md
    - internals: lib/internals.md
