site_name:        PhyloPlots.jl
repo_url:         https://github.com/cecileane/PhyloPlots.jl
site_description: Display utilities for phylogenetic trees and networks
site_author:      C&eacute;cile An&eacute;

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent:  'teal'
  logo: 'snaq_small.png'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite

docs_dir: 'build'

pages:
  - home: index.md
  - library:
    - public: lib/public.md
    - internals: lib/internals.md
